### PR TITLE
fix(CarouselIndicators): li key values generate from provided item va…

### LINKED ISSUE #1310: [CarouselIndicators] Warning: Encountered two children with the same key
- components: `CarouselIndicators`
- reactstrap version `^6.1.0`
- react version `^16.4.1`
- bootstrap version `^4.1.0`

### What is happening?

When you pass your data to 
```
<CarouselIndicators items={items} activeIndex={activeIndex} onClickHandler={this.goToIndex} />
```

It provoke

screenshot 2018-11-28 at 15 46 26

### What should be happening?

CarouselIndicators shouldn't rely on dataset implementation (which is not using src)

### Error message in console

screenshot 2018-11-28 at 15 46 26

### Code

```
<CarouselIndicators items={items} activeIndex={activeIndex} onClickHandler={this.goToIndex} />
```

### PR DESCRIPTION
**Pull request by wlockiv**
…lues

Generation of key items for `li` components in `CarouselIndicators` is a
concatenation of specific, optional values (`src`, `caption`, and
`altText`) in each item of the `items` object array. Lacking these
key/value pairs will cause each `li` element to have a key along the
lines of `undefinedundefinedundefined`, resulting two or more of the
`li`'s to be identical and causing an error to log in the console.
While either including any one of the specified keys with a unique
value, or adding a unique `key` field in each of the items objects will
remedy this issue, that solution is not well documented. The proposed
solution is a transparent fix: preventing the aforementioned error while
requiring no change of code for the end-user. The new `key` prop value
for each `li` will be a concatenation of all the values of its
respective item object.

Closes #1310

- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- - [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/CarouselIndicators.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ const CarouselIndicators = (props) => {
     ), cssModule);
     return (
       <li
-        key={`${item.key || item.src}${item.caption}${item.altText}`}
+        key={`${Object.values(item).join('')}`}
```
Comment (TheSharpieOne) [inline src/CarouselIndicators.js]: It would still be good to explicitly allow the key to be the key specified if specified. In the case where other values change but the user wants to ensure its the same instance of the component, an explicit key would be the only way to ensure that.

Comment (wlockiv) [reply src/CarouselIndicators.js]: 100% Agree. What about something like this?

```suggestion
        key={`${item.key || Object.values(item).join('')}`}
```

Comment (TheSharpieOne) [reply src/CarouselIndicators.js]: Yes, exactly.
