### PR TITLE
fix(Progress): Fix parent element props being spread to children

### LINKED ISSUE #1969: Duplicate id being rendered for Progress component
- components: `Progress`
- reactstrap version `8.6.0`

### What is happening?

If you pass an id to `Progress`, this will be added to both the outer progress element along with the inner progress bar element.  This is caused by a change in #1919.

### What should be happening?

id should not be duplicated.

### Code

`<Progress id="test" />`

### PR DESCRIPTION
**Pull request by kyletsang**
- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- - [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Fixes #1969

This also adds to ability to customize the progress bar element via tag

### CODE REVIEW

File: src/Progress.js [hunk 1]
```diff
@@ -75,30 +75,34 @@ const Progress = (props) => {
...
+        {...attributes}
+        {...progressBarProps} 
+      />
+    );
   }
 
   return (
-    <Tag {...attributes} className={progressClasses} children={ProgressBar} />
+    <Tag {...attributes} className={progressClasses}>
+      {multi ? children : <div {...progressBarProps} />}
```
Comment (kyletsang) [inline src/Progress.js:104]: I don't think having props `bar` and `multi` together would be valid, so this condition is moved down here.
