### PR TITLE
fix(#2662): remove many instances of default props

### LINKED ISSUE #2662: Warning: Container: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
React seems to be going away from defaultProps, and we should use default parameters instead

```
const defaultProps = {
  tag: 'div',
};
//Remove above and add like this i assume?
function Container(props) {
  const { className, cssModule, fluid, tag: Tag = 'div', ...attributes } = props;
```

Low hanging fruit for new contributor to carry out?

### PR DESCRIPTION
**Pull request by amillward**
- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] My change requires a change to [Typescript typings](./types/lib).
  - [ ] I have updated the typings accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Partially fixes #2662

### CODE REVIEW

**Comment by amillward** [comment]
I'm aware this doesn't fully address `defaultProps` for all components (I am too time-poor right now to do the more complex cases) but hopefully this is a start as this warning is now extremely noisy

File: src/ButtonToggle.js [hunk 1]
```diff
@@ -13,12 +13,8 @@ const propTypes = {
   cssModule: PropTypes.object,
 };
 
-const defaultProps = {
-  defaultValue: false,
-};
-
 function ButtonToggle(props) {
-  const [toggled, setToggled] = useState(props.defaultValue);
+  const [toggled, setToggled] = useState(props.defaultValue || false);
```
Comment (illiteratewriter) [inline src/ButtonToggle.js:17]: Would the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) be a better choice here?

File: src/CardTitle.js [hunk 2]
```diff
@@ -12,12 +12,8 @@ const propTypes = {
   tag: tagPropType,
 };
 
-const defaultProps = {
-  tag: 'div',
-};
-
 function CardTitle(props) {
-  const { className, cssModule, tag: Tag, ...attributes } = props;
+  const { className, cssModule, tag: Tag = 'div', ...attributes } = props;
```
Comment (illiteratewriter) [inline src/CardTitle.js:16]: Since this is a title, I think it'd be better to use `h5` or something here.

File: src/DropdownItem.js [hunk 3]
```diff
@@ -42,7 +37,7 @@ class DropdownItem extends React.Component {
       this.props.onClick(e);
     }
 
-    if (this.props.toggle) {
+    if (this.props.toggle || true) {
```
Comment (illiteratewriter) [inline src/DropdownItem.js:40]: Here too, I think we can use [??](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing)

File: src/Fade.js
Comment (illiteratewriter) [inline src/Fade.js:1]: Can we remove `Fade.defaultProps = defaultProps` for this file?

File: src/NavbarToggler.js [hunk 4]
```diff
@@ -15,21 +15,16 @@ const propTypes = {
...
+  const { className, cssModule, children, tag: Tag = 'button', ...attributes } = props;
 
   const classes = mapToCssModules(
     classNames(className, 'navbar-toggler'),
     cssModule,
   );
 
   return (
-    <Tag aria-label="Toggle navigation" {...attributes} className={classes}>
+    <Tag aria-label="Toggle navigation" {...{type: 'button',...attributes}} className={classes}>
```
Comment (illiteratewriter) [inline src/NavbarToggler.js:27]: Do we need to do `{...{type: 'button',...attributes}}`? Shouldn't just `{type: 'button',...attributes}` work?

File: src/Toast.js [hunk 5]
```diff
@@ -33,11 +30,11 @@ function Toast(props) {
   const {
     className,
     cssModule,
-    tag: Tag,
-    isOpen,
+    tag: Tag = 'div',
+    isOpen = true,
     children,
     transition,
```
Comment (illiteratewriter) [inline src/Toast.js:36]: We can add `transition` also as a default parameter right? Is there any issue in doing so and removing `Toast.defaultProps`?

**Review by illiteratewriter — CHANGES_REQUESTED** [review]

**Review by illiteratewriter — CHANGES_REQUESTED** [review]

**Comment by illiteratewriter** [comment]
Thank you so much for the PR.

I added comments earlier instead of a review. Sorry about that.

Also, Reactstrap uses `eslint` for [linting](https://www.freecodecamp.org/news/what-is-linting-and-how-can-it-save-you-time/), and `prettier` for code styles. 
If you run `yarn lint` before making any code changes now, you'll be able to see a couple of errors. Eslint helps with such small errors.
Also, once you're done; run `yarn prettier`. It keeps code style consistent across the project.

File: src/CardTitle.js (hunk 2 above)
Comment (amillward) [reply src/CardTitle.js:16]: My intention is to not change any behaviour with this pr. The original default value is `div` which I have preserved.

File: src/Fade.js
Comment (amillward) [reply src/Fade.js:1]: `Fade.defaultProps` is used in a number of other modules so would take a decent chunk more time to remove which I don't have right now - sorry!

File: src/NavbarToggler.js (hunk 4 above)
Comment (amillward) [reply src/NavbarToggler.js:27]: `{type: 'button',...attributes}` defaults `type` if it's not present in `attributes`. The wrapping `{...obj}` spreads the resulting object to be rendered as html attributes

File: src/Toast.js (hunk 5 above)
Comment (amillward) [reply src/Toast.js:36]: I was lazy and avoided this as it is not a simple case. I think it needs a deep merge because there are nested objects. Simply doing 
```
transition = {
    ...Fade.defaultProps,
    unmountOnExit: true,
  }
```

would not allow for, e.g. prop of `{transition: {appear: false}}`. `transition` wouldn't be empty, so it would lose all the other defaultProp values

**Comment by amillward** [comment]
@illiteratewriter thanks for the feedback. I have responded to them all. Happy to discuss any further :)

File: src/Toast.js (hunk 5 above)
Comment (TheSharpieOne) [reply src/Toast.js:36]: > I was lazy and avoided this as it is not a simple case. I think it needs a deep merge because there are nested objects. Simply doing
> 
> ```
> transition = {
>     ...Fade.defaultProps,
>     unmountOnExit: true,
>   }
> ```
> 
> would not allow for, e.g. prop of `{transition: {appear: false}}`. `transition` wouldn't be empty, so it would lose all the other defaultProp values

That is how default props work now; defaultProps doesn't merge objects, it just uses the default if the prop is `undefined`. Later in the code, a shallow merge is done to add any missing default values on the object root (which, looking at the Fade component, is all that really matters.) Maybe `unmountOnExit: true,` should be added there (but that would technically be a change to how it currently would work.)

Comment (amillward) [reply src/Toast.js]: @TheSharpieOne ah I did not realise that (I've never used `defaultProps` myself). I've updated in this instance. Thank you

**Comment by singleseeker** [comment]
@illiteratewriter Hi, what's next? Do you plan to merge this PR?

**Review by illiteratewriter — APPROVED** [review]
