### PR TITLE
fix(Tooltip): Support for multiple target elements

### LINKED ISSUE #1185: Tooltip only show for first element
reactstrap version 6.4
react verison 16.4.2
bootstrap 4

In cases where there are elements with the same ID created through a loop or rendered from reusable components, the tooltip only show for the first element with the ID.

I try to fix it myself but I lack the knowledge of reading other people's code. The issue, I suspect lies here

```
function getTarget(target) {
  var els = findDOMElements(target);
  if (isArrayOrNodeList(els)) {
    return els[0];
  }
  return els;
}
```

It's always returning the first element of the list, even when there are more than one elements. In the original bootstrap 4, it initializes tooltip for any elements with the attribute `data-toggle` (from the example), thus allowing same tooltip to show on different same elements. Consider using a loop to loop through `NodeList` and apply the `addEventListener`.

### PR DESCRIPTION
**Pull request by akhlesh**
It fixes #1185 
Here is stackblitz demo with fix - https://stackblitz.com/edit/react-k8rkzv

- [x] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [x] There is an open issue which this change addresses
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- - [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Kliton** [comment]
Up

File: src/TooltipPopoverWrapper.js [hunk 1]
```diff
@@ -231,54 +250,55 @@ class TooltipPopoverWrapper extends React.Component {
...
+      this.removeEventOnTargets('focusout', this.hide, true);
     }
 
     document.removeEventListener('click', this.handleDocumentClick, true)
   }
 
   updateTarget() {
-    const newTarget = getTarget(this.props.target);
-    if (newTarget !== this._target) {
+    const newTarget = getTarget(this.props.target, true);
```
Comment (felixfbecker) [inline src/TooltipPopoverWrapper.js]: This PR broke support for refs as `target` prop. When `props.target` is a React ref or an HTMLElement, this will return an HTMLElement, not an array. `Array.from(newTarget)` will then return an empty array, and Popper will error that `target` was set to `undefined`.

File: src/TooltipPopoverWrapper.js [hunk 2]
```diff
@@ -231,54 +250,55 @@ class TooltipPopoverWrapper extends React.Component {
...
+    if (newTarget !== this._targets) {
```
Comment (felixfbecker) [inline src/TooltipPopoverWrapper.js]: Using reference equality here to compare two arrays doesn't look right

File: src/TooltipPopoverWrapper.js (hunk 1 above)
Comment (TheSharpieOne) [reply src/TooltipPopoverWrapper.js]: fixed in #1687

File: src/TooltipPopoverWrapper.js (hunk 2 above)
Comment (TheSharpieOne) [reply src/TooltipPopoverWrapper.js]: Yes, it seems like this would always be `true` since we would be getting a new array from `getTarget` every time. Probably need to perform a deep comparison here.

Comment (felixfbecker) [reply src/TooltipPopoverWrapper.js]: And then only remove the event listeners from the targets that actually got removed (vs removing from all the targets if one was removed)

Comment (TheSharpieOne) [reply src/TooltipPopoverWrapper.js]: it might be easier _and quicker_ to just remove them all and add the newTarget back 🤷‍♂

Comment (felixfbecker) [reply src/TooltipPopoverWrapper.js]: True
