### PR TITLE
fix(FormGroup): dont pass switch prop to tag #2415

### LINKED ISSUE #2415: FormGroup: Using switch prop results in warning: Received `true` for a non-boolean attribute `switch`
- components: `name`
- reactstrap version `#9.0.1`
- import method `typescript, import { FormGroup } from 'reactstrap' - whichever that is :)`
- react version `#17.0.2`
- bootstrap version `#5.1.3`

### What is happening?

When using the `switch` prop with `FormGroup`:

```
<FormGroup switch>
...
</FormGroup>
```

I get this warning in the browser:

```
Warning: Received `true` for a non-boolean attribute `switch`.
      
      If you want to write it to the DOM, pass a string instead: switch="true" or switch={value.toString()}.
          at div
          at FormGroup (C:\dev\Portal\src\Coeo.Portal\clientapp\node_modules\reactstrap\src\FormGroup.js:25:5)
         ...
```

### What should be happening?

No warnings should be displayed.

### Steps to reproduce issue

1. Create a `FormGroup` and set the `switch` prop.
2. Run the app

### Error message in console

See above.

### Code

https://reactstrap-py5tda.stackblitz.io

(Check the console pane to see the warning)

### PR DESCRIPTION
**Pull request by mikegoatly**
- [X] Bug fix 
- [ ] New feature 
- [ ] Chore 
- [ ] Breaking change 
- [X] There is an open issue which this change addresses
- [X] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [x] My commits follow the [Git Commit Guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [X] My change requires a change to [Typescript typings](./types/lib).
  - [X] I have updated the typings accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

Fixes #2415 - I also noticed that the typings didn't include the `switch` prop, so I've added it for completeness.

### CODE REVIEW

File: src/FormGroup.js [hunk 1]
```diff
@@ -30,16 +30,17 @@ const FormGroup = (props) => {
     inline,
     floating,
     tag: Tag,
+    switch: switchProp,
```
Comment (davidacevedo) [inline src/FormGroup.js:33]: Can you leave this as `switch` instead of `switchProp`?

Comment (mikegoatly) [reply src/FormGroup.js:33]: Unfortunately not - doing so means you end up with ambiguity between the `switch` variable and JavaScript  `switch`/`case` statement - I can call it something else if you'd prefer, e.g. `_switch`?

Comment (jfhenon) [reply src/FormGroup.js:33]: Hello, It would be nice to see this ugly error message fixed.
Maybe a comment to explain the variable name would be good to approve this merge? 
The other way is to keep the props.switch notation?
Thanks

Comment (mikegoatly) [reply src/FormGroup.js:33]: We can't leave it as `props.switch` - destructuring the prop like this fixes the issue - without it `switch` remains in the `attributes` object that is passed through to the underlying control.

As I say, I'm very happy to use whatever name is deemed appropriate, but as far as I know this PR hasn't even been looked at by any of the maintainers, so I don't think that's what's causing it to be left unmerged.

Comment (jfhenon) [reply src/FormGroup.js:33]: workaround: you can remove the switch prop from FormGroup and replace with the bootstrap classname:
` <FormGroup className="form-check form-switch">`

Comment (davidacevedo) [reply src/FormGroup.js:33]: Had forgotten to respond, the PR looks good 👍

**Review by davidacevedo — APPROVED** [review]
